site_name: naics-embedder
site_description: Hyperbolic contrastive learning and HGCN refinement for NAICS taxonomy
site_author: Lowell Mason
site_url: https://lowmason.github.io/naics-embedder/
repo_name: lowmason/naics-embedder
repo_url: https://github.com/lowmason/naics-embedder

theme:
  name: mkdocs 
  language: en
  features:
    - awesome-nav

  palette:
    - scheme: slate
      primary: teal
      accent: cyan

  extra_css:
    - css/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.mark

plugins:
  - awesome-nav
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_full_path: false
